# Site settings
name: 韩泊骁
location: 石家庄
company: 石家庄铁道大学
position: 软件工程
github: https://github.com/iZywen
facebook: https://www.facebook.com/
phone: 18131723536
email: 2283016384@qq.com

baseurl: ""

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

